# Generated by Django 4.2.1 on 2023-05-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousal')),
                ('title', models.CharField(max_length=225)),
                ('sub_title', models.CharField(max_length=500)),
                ('button_label', models.CharField(max_length=150)),
                ('button_url', models.CharField(max_length=100)),
            ],
        ),
    ]
