# Generated by Django 4.2.1 on 2023-05-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category')),
                ('title', models.CharField(max_length=225)),
                ('inner_title', models.CharField(max_length=500)),
                ('inner_subtitle', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
