# Generated by Django 4.2.1 on 2023-05-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='latest_product')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('button_label', models.CharField(max_length=150)),
                ('button_url', models.CharField(max_length=100)),
            ],
        ),
    ]
