# Generated by Django 4.2.1 on 2023-05-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_latest_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='latest_product',
        ),
    ]
