# Generated by Django 4.2.1 on 2023-05-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_latest_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('sub_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
