# Generated by Django 4.2.1 on 2023-05-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='abouthome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='abouthome')),
                ('title', models.CharField(max_length=225)),
                ('sub_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='about',
        ),
    ]
