# Generated by Django 4.2.1 on 2023-05-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_abouthome_delete_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouthome',
            name='image',
        ),
    ]
