# Generated by Django 4.2.1 on 2023-05-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='some description', max_length=225),
            preserve_default=False,
        ),
    ]
