# Generated by Django 4.2.1 on 2023-05-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo_slider')),
            ],
        ),
    ]
